# Generated by Django 4.0.2 on 2022-02-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xcoor', models.DecimalField(decimal_places=3, max_digits=9)),
                ('ycoor', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
        ),
    ]
